name: Deploy API App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22222
          command_timeout: 20m
          script: |
            cd /home/yota/repositories/iglesia/iglesia.ui 
            git fetch origin master --force
            echo "✅ Cambios detectados en master"
            git checkout master
            git reset --hard origin/master
            chmod +x ./run-api-prod.sh
            ./run-api-prod.sh


            
